### ISSUE TITLE
Error Building: Invalid __declspec declaration

### ISSUE THREAD

**Issue by ArmstrongJ** [open-watcom/open-watcom-v2#242]
I'm seeing build issues (after a full clean) building with Open Watcom on Linux:

```
==== 21:44:45 /home/jeff/workspace/watcom/open-watcom-v2/bld/w32api/nt386 =====
awk -v cpu=386 -f ../def2lbc.awk -v OUTFILE=aclui.lbc ../lib/aclui.def
bwlib -q -b-n-pa -s-t-zld -ii  -io   aclui.lib @aclui.lbc
cc adsiid.obj
/home/jeff/workspace/watcom/open-watcom-v2/bld/hdr/dos/stdlib.h(188): Error! E1169: Invalid __declspec declaration
/home/jeff/workspace/watcom/open-watcom-v2/bld/hdr/dos/stdlib.h(224): Error! E1169: Invalid __declspec declaration
/home/jeff/workspace/watcom/open-watcom-v2/bld/hdr/dos/stdlib.h(225): Error! E1169: Invalid __declspec declaration
/home/jeff/workspace/watcom/open-watcom-v2/bld/hdr/dos/stdlib.h(244): Error! E1169: Invalid __declspec declaration
Error(E42): Last command making (adsiid.obj) returned a bad status
Error(E02): Make execution terminated
<pmake -d build         -h> => non-zero return: 512
Build failed
```

Probably a recent change, but I just wanted to let everyone know...

**Comment by jmalak** [comment]
It is strange. It looks like you are using old version of build C compiler bwcc...
Check if bld/build/bin is realy blank after cleaning before start build. Build compiler need support for __declspec(noreturn) modifier and it looks like your's doesn't have it.
This functionality was introduced by 6fea628ea0d2669907e25d79aefefc1f3bc9c4ca

**Comment by ArmstrongJ** [comment]
This report was my mistake.  I was using incompatible versions of `stdlib.h` with an older compiler build due to some inconsistencies in my build environment.  There's no issue to report.
